package codexsites

const indexHTML = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Gedung Peristiwa — Malaysia Transit Live</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><link rel="stylesheet" href="/app.css">
</head><body><div class="layout"><aside id="sidebar">
<h1>Gedung Peristiwa</h1><p class="sub"><a href="/replay">Historical replay →</a></p><p class="sub" id="region-subtitle"></p>
<h2>Region</h2><div id="region-list"></div><h2>Tenants</h2><ul class="tenant-list" id="tenant-list"></ul>
<h2>Stats</h2><div class="stats"><p>Vehicles: <span id="vehicle-count">0</span></p><p>Updated: <span id="last-update">—</span></p><p>Events: <span id="event-count">0</span></p></div>
<button type="button" id="poll-now" class="poll-button">Poll GTFS → R2</button><p id="poll-status" class="status">Storage: R2 · Projection: D1</p>
<label class="debug-toggle"><input type="checkbox" id="debug-ingest"> Debug ingest</label><p id="stream-status" class="status">Loading…</p>
</aside><div id="map-wrap"><div id="map"></div><div id="ingest-overlay"></div></div></div>
<script src="/config.js"></script><script src="/app.js"></script></body></html>`

const replayHTML = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Gedung Peristiwa — Historical Replay</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><link rel="stylesheet" href="/app.css">
</head><body><div class="layout"><aside id="sidebar"><h1>Historical replay</h1><p class="sub"><a href="/">← Live map</a></p><p class="sub" id="region-subtitle"></p>
<h2>Region</h2><div id="region-list"></div><h2>Snapshots in R2</h2><div id="catalog-empty" class="empty-msg"></div><div id="catalog"></div>
<h2>Playback</h2><div class="controls"><button id="btn-play">Play</button><button id="btn-stop" disabled>Stop</button><select id="speed"><option value="1">1×</option><option value="10" selected>10×</option><option value="60">60×</option></select></div>
<p id="replay-status" class="status">Loading catalog…</p><ul class="notes" id="catalog-notes"></ul></aside><div id="map-wrap"><div id="map"></div></div></div>
<script src="/config.js"></script><script src="/replay.js"></script></body></html>`

const appCSS = `:root{--bg:#0d1117;--panel:#161b22;--text:#e6edf3;--muted:#8b949e;--border:#30363d;--accent:#58a6ff}*{box-sizing:border-box}body{margin:0;font-family:system-ui,sans-serif;background:var(--bg);color:var(--text)}.layout{display:flex;height:100vh}aside{width:300px;background:var(--panel);border-right:1px solid var(--border);padding:1rem;overflow-y:auto;flex-shrink:0}aside h1{font-size:1rem;margin:0 0 .5rem}aside h2{font-size:.85rem;color:var(--muted);margin:1rem 0 .5rem;text-transform:uppercase;letter-spacing:.05em}#map-wrap{flex:1;min-height:0;position:relative}#map{width:100%;height:100%}.sub{color:var(--muted);font-size:.8rem;margin-bottom:1rem}.sub a,a{color:var(--accent)}.stats p{margin:.35rem 0;font-size:.9rem}.stats span{font-weight:600}.status{font-size:.8rem;color:var(--muted);margin-top:.5rem}.status.ok{color:#3fb950}.status.err,.empty-msg{color:#f85149}.region-btn{display:block;width:100%;text-align:left;margin:.2rem 0;padding:.45rem .6rem;border:1px solid var(--border);border-radius:6px;background:transparent;color:var(--text);cursor:pointer;font-size:.85rem}.region-btn.active{border-color:var(--accent);background:#58a6ff1f}.tenant-list{font-size:.8rem;color:var(--muted);margin:0;padding-left:1rem}.tenant-list li{margin:.15rem 0}.debug-toggle{font-size:.8rem;margin-top:1rem}.poll-button{width:100%;margin-top:1rem;padding:.55rem .6rem;border:1px solid var(--accent);border-radius:6px;background:#58a6ff1f;color:var(--text);cursor:pointer;font-weight:600}.poll-button:disabled{opacity:.5;cursor:wait}.controls{display:flex;gap:.35rem;flex-wrap:wrap}.controls button,.controls select{font-size:.8rem;padding:.35rem .5rem;border-radius:6px;border:1px solid var(--border);background:var(--panel);color:var(--text);cursor:pointer}.controls button:disabled{opacity:.5;cursor:not-allowed}.catalog-agency{margin-bottom:.75rem;font-size:.8rem}.catalog-agency h3{margin:0 0 .25rem;font-size:.8rem}.muted,.notes{color:var(--muted)}.snap-row{font-family:ui-monospace,monospace;font-size:.68rem;color:var(--muted);margin:.1rem 0}.notes{font-size:.7rem;padding-left:1rem}.notes li{margin:.2rem 0}#ingest-overlay{display:none;position:absolute;right:8px;bottom:8px;max-width:360px;max-height:40vh;overflow:auto;background:#0d1117d1;border:1px solid var(--border);border-radius:6px;padding:.5rem .65rem;font:.68rem/1.35 ui-monospace,monospace;color:var(--muted);z-index:1000;pointer-events:none}#ingest-overlay.visible{display:block}`

const appJS = `(() => {
  const config=window.SITE_CONFIG, first=config.regions[0];
  const map=L.map('map',{preferCanvas:true}).setView(first.center,first.zoom);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap',maxZoom:19}).addTo(map);
  const markers={},status=document.getElementById('stream-status'),overlay=document.getElementById('ingest-overlay'),debug=document.getElementById('debug-ingest'),pollButton=document.getElementById('poll-now'),pollStatus=document.getElementById('poll-status');let active=first,agencies=new Set(first.agencies),pollInFlight=false;
  const region=id=>config.regions.find(r=>r.id===id)||first;
  function renderRegions(){document.getElementById('region-list').innerHTML=config.regions.map(r=>'<button class="region-btn '+(r.id===active.id?'active':'')+'" data-region="'+r.id+'">'+r.label+'</button>').join('');document.querySelectorAll('.region-btn').forEach(b=>b.onclick=()=>switchRegion(b.dataset.region))}
  function renderFeeds(){document.getElementById('tenant-list').innerHTML=config.feeds.filter(f=>agencies.has(f.agency)).map(f=>'<li>'+f.region+' <span style="opacity:.7">('+f.agency+')</span></li>').join('');document.getElementById('region-subtitle').textContent=active.label}
  function update(v){let m=markers[v.id],popup='<strong>'+v.agency+'</strong><br>Route: '+(v.route||'—')+'<br>Speed: '+Number(v.speed||0).toFixed(1)+' km/h';if(m)m.setLatLng([v.lat,v.lng]).setPopupContent(popup);else{m=markers[v.id]=L.circleMarker([v.lat,v.lng],{radius:7,color:'#3498db',fillColor:'#3498db',fillOpacity:.9,weight:2}).bindPopup(popup);m._agency=v.agency}if(agencies.has(v.agency)&&!map.hasLayer(m))m.addTo(map)}
  function apply(list){const seen=new Set(list.map(v=>v.id));list.forEach(update);Object.keys(markers).forEach(id=>{if(!seen.has(id)&&map.hasLayer(markers[id]))map.removeLayer(markers[id])});document.getElementById('vehicle-count').textContent=list.length;status.textContent='Live — '+list.length+' vehicles';status.className='status ok'}
  function ingestView(d){if(!debug.checked)return;overlay.className='visible';overlay.innerHTML='<strong>Ingest — '+(d.activeLabel||active.label)+'</strong><br>'+(d.records||[]).map(r=>r.agency+' '+r.vehicle+' '+Number(r.lat).toFixed(2)+','+Number(r.lng).toFixed(2)+' '+r.at).join('<br>')}
  function applyStats(d){document.getElementById('last-update').textContent=d.lastUpdate||'—';document.getElementById('event-count').textContent=d.eventCount||0}
  async function refreshVehicles(){const [vehiclesRes,statsRes]=await Promise.all([fetch('/api/vehicles'),fetch('/api/status')]);if(!vehiclesRes.ok||!statsRes.ok)throw new Error('projection refresh failed');apply(await vehiclesRes.json());applyStats(await statsRes.json());status.textContent='Live';status.className='status ok'}
  async function pollGTFS(){if(pollInFlight)return;pollInFlight=true;pollButton.disabled=true;pollStatus.textContent='Calling GTFS feeds…';pollStatus.className='status';try{const res=await fetch('/api/poll',{method:'POST'}),data=await res.json();if(!res.ok)throw new Error(data.error||'poll failed');const failures=data.errors&&data.errors.length?' · '+data.errors.length+' feed errors':'';pollStatus.textContent='GTFS → R2: '+data.accepted+' positions ('+data.feeds+' feeds)'+failures+' · '+data.r2Key;pollStatus.className=data.errors&&data.errors.length?'status err':'status ok';await refreshVehicles()}catch(e){pollStatus.textContent='GTFS poll failed: '+e.message;pollStatus.className='status err';status.textContent='Refresh failed';status.className='status err'}finally{pollInFlight=false;pollButton.disabled=false}}
  async function switchRegion(id){const r=region(id),res=await fetch('/api/region',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:id})});if(!res.ok)return;active=r;agencies=new Set(r.agencies);renderRegions();renderFeeds();map.flyTo(r.center,r.zoom,{duration:1});try{await refreshVehicles()}catch(e){status.textContent='Refresh failed';status.className='status err'}}
  pollButton.onclick=()=>{void pollGTFS()};debug.onchange=()=>{overlay.classList.toggle('visible',debug.checked);if(!debug.checked)overlay.innerHTML=''};renderRegions();renderFeeds();setTimeout(()=>{void pollGTFS()},150);setInterval(()=>{void pollGTFS()},30000);
})()`

const replayJS = `(() => {
  const config=window.SITE_CONFIG,first=config.regions[0],map=L.map('map',{preferCanvas:true}).setView(first.center,first.zoom);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);const markers={};let current=first.id,source;
  const region=id=>config.regions.find(r=>r.id===id)||first;
  function buttons(){document.getElementById('region-list').innerHTML=config.regions.map(r=>'<button class="region-btn '+(r.id===current?'active':'')+'" data-region="'+r.id+'">'+r.label+'</button>').join('');document.querySelectorAll('.region-btn').forEach(b=>b.onclick=()=>switchRegion(b.dataset.region))}
  function clear(){Object.values(markers).forEach(m=>map.removeLayer(m));Object.keys(markers).forEach(k=>delete markers[k])}
  function apply(list){const seen=new Set();list.forEach(v=>{seen.add(v.id);if(markers[v.id])markers[v.id].setLatLng([v.lat,v.lng]);else markers[v.id]=L.circleMarker([v.lat,v.lng],{radius:5,color:'#58a6ff',fillOpacity:.85}).addTo(map).bindPopup(v.agency+' — '+(v.route||v.id))});Object.keys(markers).forEach(id=>{if(!seen.has(id)){map.removeLayer(markers[id]);delete markers[id]}})}
  function render(d){const c=document.getElementById('catalog'),n=document.getElementById('catalog-notes'),e=document.getElementById('catalog-empty');c.innerHTML='';n.innerHTML='';e.textContent=d.empty?(d.message||'No snapshot data for this region.'):'';(d.notes||[]).forEach(x=>{const li=document.createElement('li');li.textContent=x;n.appendChild(li)});(d.agencies||[]).forEach(a=>{const b=document.createElement('div');b.className='catalog-agency';b.innerHTML='<h3>'+a.agency+' ('+a.count+')</h3>';(a.snapshots||[]).slice(0,8).forEach(s=>{const row=document.createElement('div');row.className='snap-row';row.textContent=(s.at?new Date(s.at).toISOString():'—')+' · '+s.source+' · '+s.s3Key;b.appendChild(row)});c.appendChild(b)})}
  async function catalog(){const s=document.getElementById('replay-status'),r=await fetch('/api/replay/catalog?region='+encodeURIComponent(current));if(!r.ok){s.textContent='Catalog failed';s.className='status err';return}const d=await r.json();render(d);s.textContent=d.empty?'No snapshots to replay.':'Loaded '+d.total+' snapshot(s). Press Play.';s.className=d.empty?'status err':'status ok'}
  async function switchRegion(id){current=id;const r=region(id);document.getElementById('region-subtitle').textContent=r.label;buttons();map.flyTo(r.center,r.zoom,{duration:.8});clear();stop();await catalog()}
  function stop(){if(source){source.close();source=null}document.getElementById('btn-play').disabled=false;document.getElementById('btn-stop').disabled=true}
  function play(){stop();const s=document.getElementById('replay-status'),speed=document.getElementById('speed').value;source=new EventSource('/api/replay/stream?region='+encodeURIComponent(current)+'&speed='+speed);document.getElementById('btn-play').disabled=true;document.getElementById('btn-stop').disabled=false;source.addEventListener('vehicles',e=>apply(JSON.parse(e.data)));source.addEventListener('progress',e=>{const p=JSON.parse(e.data);if(p.status!=='starting'){s.textContent='Frame '+p.frame+' / '+p.total+(p.at?' · '+p.at:'');s.className='status ok'}});source.addEventListener('done',()=>{s.textContent='Replay complete.';stop()});source.addEventListener('error',()=>{s.textContent='Replay error';s.className='status err';stop()})}
  document.getElementById('btn-play').onclick=play;document.getElementById('btn-stop').onclick=stop;document.getElementById('region-subtitle').textContent=first.label;buttons();catalog();
})()`

const schemaSQL = `CREATE TABLE IF NOT EXISTS sessions (session_id TEXT PRIMARY KEY, region_id TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS vehicle_positions (vehicle_key TEXT PRIMARY KEY, agency TEXT NOT NULL, vehicle_id TEXT NOT NULL, region_id TEXT NOT NULL, lat REAL NOT NULL, lng REAL NOT NULL, route TEXT NOT NULL DEFAULT '', speed REAL NOT NULL DEFAULT 0, bearing REAL NOT NULL DEFAULT 0, vehicle_group TEXT NOT NULL DEFAULT '', timestamp_ms INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS ingest_events (id TEXT PRIMARY KEY, agency TEXT NOT NULL, region_id TEXT NOT NULL, vehicle_id TEXT NOT NULL, lat REAL NOT NULL, lng REAL NOT NULL, occurred_at INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS snapshots (id TEXT PRIMARY KEY, agency TEXT NOT NULL, region_id TEXT NOT NULL, source TEXT NOT NULL, r2_key TEXT NOT NULL, at_ms INTEGER NOT NULL, watermark_ns INTEGER NOT NULL DEFAULT 0, size INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS poll_state (id INTEGER PRIMARY KEY CHECK (id = 1), last_poll_ms INTEGER NOT NULL DEFAULT 0, event_count INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_positions_region_agency ON vehicle_positions(region_id, agency);
CREATE INDEX IF NOT EXISTS idx_ingest_region_created ON ingest_events(region_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_region_at ON snapshots(region_id, at_ms);
INSERT OR IGNORE INTO poll_state(id) VALUES (1);`

const wranglerJSONC = `{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "gedung-peristiwa-sites",
  "main": "worker.ts",
  "compatibility_date": "2026-08-06",
  "assets": { "directory": "./public", "binding": "ASSETS" },
  "d1_databases": [{ "binding": "DB", "database_name": "gedung-peristiwa", "database_id": "REPLACE_WITH_D1_DATABASE_ID" }],
  "r2_buckets": [{ "binding": "EVENTS", "bucket_name": "gedung-peristiwa-events" }],
  "vars": { "SITE_NAME": "Gedung Peristiwa" }
}`

const readmeMD = `# Gedung Peristiwa — Codex Sites bundle

Generated by go run ./cmd/codex-sites. The codex-sites/ directory is disposable and ignored by git.

This is a Cloudflare Worker version of the current transit UI. It keeps the existing browser API contract, but uses D1 for sessions, latest vehicle projections, ingest records, poll counters, and replay catalog rows; and R2 for immutable JSON ingest batches and replay payloads. R2 is the MinIO replacement for this generated deployment.

## Generate and deploy

    go run ./cmd/codex-sites
    cd codex-sites
    npx wrangler d1 create gedung-peristiwa
    # Put the returned database_id in wrangler.jsonc
    npx wrangler d1 execute gedung-peristiwa --remote --file=schema.sql
    npx wrangler secret put INGEST_TOKEN
    npx wrangler deploy

The generated Worker expects D1 and R2 bindings named DB and EVENTS. POST /api/poll fetches the current region's GTFS-Realtime protobuf feeds directly from api.data.gov.my, decodes vehicle positions, writes the immutable raw batch to R2, and updates the D1 projection. The live page polls automatically every 30 seconds; Poll GTFS → R2 is also available for an immediate refresh. POST /api/ingest remains available for the Go poller or other trusted producers; set INGEST_TOKEN to protect it.

This is an isolated deployment target. It does not alter or import the existing IsleDB/MinIO runtime. Re-run the compiler whenever the current Go region/feed configuration changes.
`

const workerTS = `type Region = { id:string; label:string; center:[number,number]; zoom:number; agencies:string[] };
type Feed = { agency:string; region:string; group:string; url:string };
type Position = { id:string; lat:number; lng:number; agency:string; group?:string; route?:string; speed?:number; bearing?:number; timestamp?:string };
type Env = { DB:D1Database; EVENTS:R2Bucket; ASSETS:Fetcher; INGEST_TOKEN?:string; SITE_NAME?:string };

const SITE_DATA = __REGIONS_JSON__;
const REGIONS:Region[] = SITE_DATA.regions;
const FEEDS:Feed[] = SITE_DATA.feeds;
const regionByID = (id:string) => REGIONS.find(r=>r.id===id) ?? REGIONS[0];
const json = (value:unknown, init:ResponseInit={}) => new Response(JSON.stringify(value),{...init,headers:{'content-type':'application/json; charset=utf-8',...(init.headers||{})}});
const now = () => Date.now();
const cookieID = (request:Request) => request.headers.get('Cookie')?.match(/(?:^|;\s*)demo_sid=([^;]+)/)?.[1] || crypto.randomUUID();
const withCookie = (response:Response, sid:string) => { const h=new Headers(response.headers);h.append('Set-Cookie','demo_sid='+sid+'; Path=/; HttpOnly; SameSite=Lax; Secure');return new Response(response.body,{status:response.status,headers:h}) };
const agenciesFor = (id:string) => new Set(regionByID(id).agencies);
const sse = (event:string,data:unknown) => 'event: '+event+'\ndata: '+JSON.stringify(data)+'\n\n';
const sleep = (ms:number) => new Promise<void>(resolve=>setTimeout(resolve,ms));
function readVarint(bytes:Uint8Array,offset:number){let value=0,shift=0;while(offset<bytes.length){const b=bytes[offset++];value+=(b&127)*Math.pow(2,shift);if(!(b&128))return{value,offset};shift+=7}return{value,offset}}
function protoFields(bytes:Uint8Array){const out:{field:number;wire:number;value:number|Uint8Array}[]=[];let offset=0;while(offset<bytes.length){const tag=readVarint(bytes,offset);offset=tag.offset;const field=Math.floor(tag.value/8),wire=tag.value&7;if(wire===0){const v=readVarint(bytes,offset);offset=v.offset;out.push({field,wire,value:v.value})}else if(wire===1){out.push({field,wire,value:bytes.slice(offset,offset+8)});offset+=8}else if(wire===2){const length=readVarint(bytes,offset);offset=length.offset;out.push({field,wire,value:bytes.slice(offset,offset+length.value)});offset+=length.value}else if(wire===5){out.push({field,wire,value:bytes.slice(offset,offset+4)});offset+=4}else break}return out}
function textField(bytes:Uint8Array,field:number){const hit=protoFields(bytes).find(f=>f.field===field&&f.wire===2);return hit?new TextDecoder().decode(hit.value as Uint8Array):''}
function bytesField(bytes:Uint8Array,field:number){const hit=protoFields(bytes).find(f=>f.field===field&&f.wire===2);return hit?.value as Uint8Array|undefined}
function floatField(bytes:Uint8Array,field:number){const hit=protoFields(bytes).find(f=>f.field===field&&f.wire===5);return hit?new DataView((hit.value as Uint8Array).buffer,(hit.value as Uint8Array).byteOffset,4).getFloat32(0,true):0}
function decodeGTFS(bytes:ArrayBuffer,feed:Feed){const data=new Uint8Array(bytes),positions:Position[]=[];for(const entity of protoFields(data).filter(f=>f.field===2&&f.wire===2)){const entityBytes=entity.value as Uint8Array,entityID=textField(entityBytes,1),vehicleBytes=bytesField(entityBytes,4);if(!vehicleBytes)continue;const positionBytes=bytesField(vehicleBytes,2);if(!positionBytes)continue;const lat=floatField(positionBytes,1),lng=floatField(positionBytes,2);if(lat<1||lat>7||lng<100||lng>119)continue;const vehicleDescriptor=bytesField(vehicleBytes,8),vehicleID=vehicleDescriptor?(textField(vehicleDescriptor,1)||textField(vehicleDescriptor,2)):entityID;if(!vehicleID)continue;const tripBytes=bytesField(vehicleBytes,1),timestampField=protoFields(vehicleBytes).find(f=>f.field===5&&f.wire===0);const timestamp=timestampField?new Date(Number(timestampField.value)*1000).toISOString():new Date().toISOString();positions.push({id:feed.agency+':'+vehicleID,agency:feed.agency,group:feed.group,lat,lng,bearing:floatField(positionBytes,3),speed:floatField(positionBytes,5),route:tripBytes?textField(tripBytes,5):'',timestamp})}return positions}

async function session(request:Request,env:Env){const sid=cookieID(request);const row=await env.DB.prepare('SELECT region_id FROM sessions WHERE session_id=?').bind(sid).first<{region_id:string}>();const regionID=row?.region_id||REGIONS[0].id;if(!row)await env.DB.prepare('INSERT INTO sessions(session_id,region_id,updated_at) VALUES(?,?,?)').bind(sid,regionID,now()).run();return{sid,regionID}}
function regionPayload(id:string){const r=regionByID(id);return{id:r.id,label:r.label,center:r.center,zoom:r.zoom,agencies:r.agencies}}
async function latest(env:Env,regionID:string){const ids=[...agenciesFor(regionID)];if(!ids.length)return[];const marks=ids.map(()=>'?').join(',');const rows=await env.DB.prepare('SELECT vehicle_key id,lat,lng,agency,vehicle_group group_name,route,speed,bearing,timestamp_ms FROM vehicle_positions WHERE agency IN ('+marks+') ORDER BY vehicle_key').bind(...ids).all<any>();return rows.results.map((v:any)=>({id:v.id,lat:v.lat,lng:v.lng,agency:v.agency,group:v.group_name,route:v.route,speed:v.speed,bearing:v.bearing,timestamp:new Date(v.timestamp_ms).toISOString()}))}
async function stats(env:Env,regionID:string){const ids=[...agenciesFor(regionID)];const marks=ids.map(()=>'?').join(',');const count=ids.length?await env.DB.prepare('SELECT COUNT(*) count FROM vehicle_positions WHERE agency IN ('+marks+')').bind(...ids).first<{count:number}>():{count:number}|null;const p=await env.DB.prepare('SELECT last_poll_ms,event_count FROM poll_state WHERE id=1').first<{last_poll_ms:number,event_count:number}>();return{vehicleCount:Number(count?.count||0),lastUpdate:p?.last_poll_ms?new Date(p.last_poll_ms).toISOString():null,eventCount:Number(p?.event_count||0)}}
async function ingest(env:Env,request:Request){if(env.INGEST_TOKEN&&request.headers.get('Authorization')!=='Bearer '+env.INGEST_TOKEN)return json({error:'unauthorized'},{status:401});const body=await request.json() as {at?:string;positions?:Position[];polledAgencies?:string[]};const positions=Array.isArray(body.positions)?body.positions:[];const at=body.at?Date.parse(body.at):now();const batchID=at+'-'+crypto.randomUUID();const r2Key='events/'+batchID+'.json';await env.EVENTS.put(r2Key,JSON.stringify({at:new Date(at).toISOString(),positions,polledAgencies:body.polledAgencies||[]} ),{httpMetadata:{contentType:'application/json'}});const statements=[];const regions=new Set<string>();for(const v of positions){const r=REGIONS.find(x=>x.agencies.includes(v.agency));if(!r||!v.id)continue;regions.add(r.id);const ts=v.timestamp?Date.parse(v.timestamp):at;statements.push(env.DB.prepare('INSERT INTO vehicle_positions(vehicle_key,agency,vehicle_id,region_id,lat,lng,route,speed,bearing,vehicle_group,timestamp_ms,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(vehicle_key) DO UPDATE SET lat=excluded.lat,lng=excluded.lng,route=excluded.route,speed=excluded.speed,bearing=excluded.bearing,timestamp_ms=excluded.timestamp_ms,updated_at=excluded.updated_at').bind(v.id,v.agency,v.id.split(':').slice(1).join(':')||v.id,r.id,Number(v.lat),Number(v.lng),v.route||'',Number(v.speed||0),Number(v.bearing||0),v.group||'',ts,now()));statements.push(env.DB.prepare('INSERT INTO ingest_events(id,agency,region_id,vehicle_id,lat,lng,occurred_at,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(batchID+':'+v.id,v.agency,r.id,v.id,Number(v.lat),Number(v.lng),ts,now()))}for(const regionID of regions){for(const agency of agenciesFor(regionID))statements.push(env.DB.prepare('INSERT INTO snapshots(id,agency,region_id,source,r2_key,at_ms,watermark_ns,size) VALUES(?,?,?,?,?,?,?,?)').bind(batchID+':'+agency,agency,regionID,'r2',r2Key,at,at*1000000,0))}statements.push(env.DB.prepare('INSERT INTO poll_state(id,last_poll_ms,event_count) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET last_poll_ms=excluded.last_poll_ms,event_count=poll_state.event_count+excluded.event_count').bind(at,positions.length));if(statements.length)await env.DB.batch(statements);return json({accepted:positions.length,r2Key})}
async function catalog(env:Env,regionID:string){const r=regionByID(regionID);const rows=await env.DB.prepare('SELECT agency,id,source,r2_key s3Key,at_ms,watermark_ns FROM snapshots WHERE region_id=? ORDER BY at_ms DESC').bind(regionID).all<any>();const grouped=new Map<string,any[]>();for(const row of rows.results){const list=grouped.get(row.agency)||[];list.push({agency:row.agency,id:row.id,source:row.source,s3Key:row.s3Key,at:row.at_ms?new Date(row.at_ms).toISOString():null,watermarkNS:row.watermark_ns});grouped.set(row.agency,list)}const agencies=r.agencies.map(agency=>({agency,count:(grouped.get(agency)||[]).length,snapshots:grouped.get(agency)||[]}));const total=agencies.reduce((n,a)=>n+a.count,0);return{regionId:regionID,label:r.label,empty:total===0,message:total===0?'No snapshot data for this region.':undefined,total,agencies,notes:['Snapshots are immutable R2 ingest batches indexed by D1.']}}
async function pollGTFS(env:Env,regionID:string){const allowed=agenciesFor(regionID),feeds=FEEDS.filter(feed=>allowed.has(feed.agency));const results=await Promise.all(feeds.map(async feed=>{try{const response=await fetch(feed.url);if(!response.ok)return{feed,positions:[],error:'HTTP '+response.status};return{feed,positions:decodeGTFS(await response.arrayBuffer(),feed),error:''}}catch(error){return{feed,positions:[],error:error instanceof Error?error.message:'fetch failed'}}}));const positions=results.flatMap(result=>result.positions);const body={at:new Date().toISOString(),positions,polledAgencies:feeds.map(feed=>feed.agency)};const headers=new Headers({'content-type':'application/json'});if(env.INGEST_TOKEN)headers.set('Authorization','Bearer '+env.INGEST_TOKEN);const stored=await ingest(env,new Request('https://internal/api/ingest',{method:'POST',headers,body:JSON.stringify(body)}));const storedBody=await stored.json() as {r2Key?:string};return json({accepted:positions.length,feeds:feeds.length,r2Key:storedBody.r2Key,errors:results.filter(result=>result.error).map(result=>({agency:result.feed.agency,error:result.error}))})}
async function liveStream(request:Request,env:Env,regionID:string){const encoder=new TextEncoder();return new ReadableStream({start(controller){let closed=false;const abort=()=>{closed=true};request.signal.addEventListener('abort',abort,{once:true});const run=async()=>{try{while(!closed){const vehicles=await latest(env,regionID),summary=await stats(env,regionID),rows=await env.DB.prepare('SELECT agency,vehicle_id vehicle,lat,lng,occurred_at at FROM ingest_events WHERE region_id=? ORDER BY created_at DESC LIMIT 10').bind(regionID).all<any>();if(closed)return;controller.enqueue(encoder.encode(sse('vehicles',vehicles)));if(closed)return;controller.enqueue(encoder.encode(sse('stats',summary)));if(closed)return;controller.enqueue(encoder.encode(sse('ingest',{activeLabel:regionByID(regionID).label,records:rows.results})));await sleep(30000)}}catch{}finally{request.signal.removeEventListener('abort',abort)}};void run()}})}
async function replayStream(env:Env,regionID:string,speed:number){const encoder=new TextEncoder();const rows=await env.DB.prepare('SELECT id,r2_key,at_ms FROM snapshots WHERE region_id=? ORDER BY at_ms ASC').bind(regionID).all<any>();return new ReadableStream({start(controller){const run=async()=>{controller.enqueue(encoder.encode(sse('progress',{frame:0,total:rows.results.length,status:'starting'})));const merged=new Map<string,Position>();for(let i=0;i<rows.results.length;i++){const object=await env.EVENTS.get(rows.results[i].r2_key);if(object){const batch=JSON.parse(await object.text()) as {positions:Position[]};for(const p of batch.positions||[])merged.set(p.id,p)}controller.enqueue(encoder.encode(sse('vehicles',[...merged.values()].filter(p=>agenciesFor(regionID).has(p.agency)))));controller.enqueue(encoder.encode(sse('progress',{frame:i+1,total:rows.results.length,at:rows.results[i].at_ms?new Date(rows.results[i].at_ms).toISOString():null,status:'playing'})));if(i+1<rows.results.length)await sleep(Math.max(0,1000/Math.max(1,speed)))}controller.enqueue(encoder.encode(sse('done',{status:'complete'})));controller.close()};run().catch(()=>{try{controller.close()}catch{}})}})}

export default {async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url),path=url.pathname;try{if(path==='/api/ingest'&&request.method==='POST')return ingest(env,request);const {sid,regionID}=await session(request,env);if(path==='/api/regions')return withCookie(json({active:regionID,regions:REGIONS.map(r=>({...regionPayload(r.id),active:r.id===regionID}))}),sid);if(path==='/api/region'){if(request.method==='POST'){const body=await request.json() as {id:string};if(!REGIONS.some(r=>r.id===body.id))return json({error:'unknown region'},{status:400});await env.DB.prepare('UPDATE sessions SET region_id=?,updated_at=? WHERE session_id=?').bind(body.id,now(),sid).run();return withCookie(json({region:regionPayload(body.id),feeds:[]}),sid)}return withCookie(json({region:regionPayload(regionID),feeds:[]}),sid)}if(path==='/api/vehicles')return withCookie(json(await latest(env,regionID)),sid);if(path==='/api/vehicles/stream'){const response=new Response(await liveStream(request,env,regionID),{headers:{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'}});return withCookie(response,sid)}if(path==='/api/replay/catalog')return withCookie(json(await catalog(env,url.searchParams.get('region')||regionID)),sid);if(path==='/api/replay/stream'){const response=new Response(await replayStream(env,url.searchParams.get('region')||regionID,Number(url.searchParams.get('speed')||1)),{headers:{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive'}});return withCookie(response,sid)}const assetPath=path==='/'?'/index.html':path==='/replay'?'/replay.html':path;return env.ASSETS.fetch(new Request(new URL(assetPath,url),request))}catch(error){return json({error:error instanceof Error?error.message:'request failed'},{status:500})}}};`
